apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: RABBITMQ_CONNECTION_STRING
        key: RABBITMQ_CONNECTION_STRING
    - name: durable
      value: "true"
    - name: deletedWhenUnused
      value: "false"
    - name: autoAck
      value: "false"
    - name: requeueInFailure
      value: "true"
    - name: reconnectWait
      value: "3"
    - name: concurrencyMode
      value: parallel
    - name: deliveryMode  # persistence setting
      value: "2"
    - name: prefetchCount # should be equal or less than the max concurrent workflows
      value: "5"
    - name: maxPriority   # set so we can prioritize some messages if wanted
      value: "3"
auth:
  secretStore: nemesis-secret-store