name: "hive_security"
description: "Link SECURITY hive to SYSTEM hive"
category: "windows"
enabled: true

triggers:
  - file_patterns:
      - "**/Windows/System32/config/SECURITY"
    magic_patterns:
      - "MS Windows registry file, NT/2000 or above"

linked_files:

  - name: "system_hive"
    description: "SYSTEM registry hive"
    path_templates:
      - 'C:\Windows\System32\config\SYSTEM'
    priority: "high"
    collection_reason: "Linked hive"
