name: "hive_system"
description: "Link SYSTEM hive to SECURITY hive"
category: "windows"
enabled: true

triggers:
  - file_patterns:
      - "**/Windows/System32/config/SYSTEM"
    magic_patterns:
      - "MS Windows registry file, NT/2000 or above"

linked_files:
  - name: "security_hive"
    description: "SECURITY registry hive"
    path_templates:
      - 'C:\Windows\System32\config\security'
    priority: "high"
    collection_reason: "Linked hive"
