apiVersion: 1

deleteDatasources:
  - name: Postgres
    orgId: 1

datasources:
  - name: Postgres
    type: postgres
    url: ${POSTGRES_CONNECTION_STRING}
    jsonData:
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1000
      timescaledb: false