global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'traefik'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['traefik:8080']

  # - job_name: 'minio'
  #   metrics_path: /minio/v2/metrics/cluster
  #   scheme: http
  #   static_configs:
  #     - targets: ['minio:9000']

  - job_name: 'prometheus'
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'postgres'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'hasura'
    metrics_path: '/v1/metrics'
    static_configs:
      - targets: ['hasura:8080']

  - job_name: 'nemesis-web-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['web-api:9090']

  - job_name: 'nemesis-noseyparker-scanner'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['noseyparker-scanner:9090']

  - job_name: 'nemesis-dotnet-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['dotnet-service:9090']

  - job_name: 'nemesis-file-enrichment'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['file-enrichment:9090']

  - job_name: 'nemesis-alerting'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['alerting:9090']

  - job_name: 'nemesis-agents'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['agents:9090']

  - job_name: 'nemesis-housekeeping'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['housekeeping:9090']

  - job_name: 'nemesis-document-conversion'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['document-conversion:9090']

  - job_name: 'nemesis-gotenberg'
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets: ['gotenberg:3000']